[package]
authors = ["Tej Chajed <tchajed@mit.edu>"]
name = "div-regex"
version = "0.1.0"
[[bin]]
name = "div-re"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
regex = "1.1.5"

[lib]
name = "div_regex"
path = "src/lib.rs"
